apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: default
spec:
  selector:
    app: application
  type: ClusterIP
  ports:
    - name: application
      protocol: TCP
      port: 3000
      targetPort: 3000