apiVersion: v1
kind: Service
metadata:
  name: semantic-service
  namespace: semantic
spec:
  selector:
    app: semantic
  type: ClusterIP
  ports:
  - name: semantic
    protocol: TCP
    port: 3000
    targetPort: 3000