name: Build and publish docker image

on:
  workflow_call:
    inputs:
      service-name:
        description: 'Name of the service, will be used as image name'
        required: true
        type: string
      environment:
        description: 'What environment is targeted, will be used for image tags'
        required: true
        type: string
        default: dev

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.service-name }}
          flavor: |
            latest=${{ inputs.environment == 'prod' }}
          tags: |
            type=sha,format=short,prefix=
            type=semver,pattern={{ version }}
            type=ref,event=branch

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max