name: Merge staging

on:
  pull_request:
    types:
      - edited
    branches:
      - main

jobs:
  merge:
    # if: ${{ github.event.pull_request.mergeable && contains(github.event.pull_request.labels.*.name, 'merge staging') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check the PR
        uses: vmonjaret/should-run-github-action@v1.0.0
        id: check-pr
        with:
          target: Merge in main
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
      - name: Checking PR name
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^chore\(([A-Z]+-[0-9]+)\)'
      - name: Debug
        run: |
          echo "regex : '${{ steps.regex-match.outputs.match == '' }}'"
          echo "shouldRun : '${{ steps.check-pr.outputs.shouldRun }}'"
      - name: Precondition PR name
        if: steps.regex-match.outputs.match == ''
        run: exit 1
      - name: Precondition should run
        if: steps.check-pr.outputs.shouldRun == 'false'
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Fast forward
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}
          git push
      # - name: Call JIRA transition
      #   run: |
      #     curl -XPOST -H 'Authorization: Basic ${{ secrets.JIRA_AUTOMATION_TOKEN }}' -H "Content-type: application/json" -d '{"transition": {"id": 31}}' 'https://coachhub.atlassian.net/rest/api/2/issue/${{ steps.regex-match.outputs.group1 }}/transitions' 
      - name: Remove label on failure
        if: ${{ failure() }}
        uses: andymckay/labeler@master
        with:
          remove-labels: "merge staging"
