name: Merge

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  merge:
    if: ${{ github.event.pull_request.mergeable && contains(github.event.pull_request.labels.*.name, 'merge staging') }}
    # if: ${{ github.event.pull_request.head.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Merging ${{ github.event.pull_request.head.ref }} into main"
          echo "Mergeable: ${{ github.event.pull_request.mergeable }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Fast forward
        run: |
          echo "Merging ${{ github.event.pull_request.head.ref }} into main"
          git checkout main
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}