name: Merge

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  merge:
    if: ${{ github.event.pull_request.mergeable && contains(github.event.pull_request.labels.*.name, 'merge staging') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR name
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^chore\(([A-Z]+-[0-9]+)\)'
      - name: Debug
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Fast forward
        run: |
          echo "Merging ${{ github.event.pull_request.head.ref }} into main"
          git checkout main
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}
          git push
      - name: Remove label on failure
        if: ${{ failure() }}
        uses: andymckay/labeler@master
        with:
          remove-labels: "merge staging"
      - name: Curl test
        run: curl --help
