name: Prerelease

on:
  push:
    branches:
      - release-*

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Prerelease
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install semantic release
        run: yarn install
      - name: Semantic Release
        run: yarn run semantic-release
