name: Release

on: workflow_dispatch

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    name: Generate release
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  backmerge:
    name: Backmerge to development
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge main in development
        run: |
          git checkout development
          git merge origin/main
          git push

  build-publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker build . --file Dockerfile --tag tmp
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        run: |
          IMAGE_ID=/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ needs.release.outputs.new_version }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag tmp ghcr.io/bazinga-tv/semantic:latest
          docker tag tmp ghcr.io/bazinga-tv/semantic:${{ needs.release.outputs.new_version }}
          docker push ghcr.io/bazinga-tv/semantic:latest
          docker push ghcr.io/bazinga-tv/semantic:${{ needs.release.outputs.new_version }}

  sentry:
    name: Create Sentry release
    runs-on: ubuntu-latest
    needs: [release, build-publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run account container
        run: docker run --name=tmp -d ghcr.io/bazinga-tv/semantic:${{ needs.release.outputs.new_version }} sh -c "while :; do echo 'Hit CTRL+C'; sleep 1; done" # Needed to avoid the container from failing
      - name: Get dist source code
        run: docker cp tmp:/usr/src/dist ./dist
      - name: Sentry Release
        run: echo "success"
