name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_AUTHOR_NAME: Vincent Monjaret
      GIT_AUTHOR_EMAIL: vmonjaret@gmail.com
      GIT_COMMITTER_NAME: Vincent Monjaret
      GIT_COMMITTER_EMAIL: vmonjaret@gmail.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  backmerge:
    name: Backmerge to development
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout development
          git merge origin master